/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ysj_yutang_ndk_JNI */

#ifndef _Included_com_ysj_yutang_ndk_JNI
#define _Included_com_ysj_yutang_ndk_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ysj_yutang_ndk_JNI
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ysj_yutang_ndk_JNI_getString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
